version: "3"

services:

  cdk:
    image: mlops-club/cdk-server-deployer
    # command: cdk synth
    #command: cdk synth '*' --app 'python3 app.py'
    command: cdk deploy '*' --app 'python3 app.py' --require-approval never
    platform: linux/amd64
    # command: cdk deploy --app 'python3 app.py' --require-approval=never
    #env_file:
    #  - .env

    environment:
      #AWS_REGION: us-west-2
      #AWS_ACCOUNT_ID: "630013828440"
      # these env vars can be grabbed from the AWS Batch UI in the Job Definition
      AWS_PROFILE: mlops-club
      AWS_REGION:	us-east-1
      SSH_KEY_PAIR_NAME:	ericriddoch
      AWS_ACCOUNT_ID:	630013828440
      MANAGED_BY_AWS:	STARTED_BY_STEP_FUNCTIONS
      BACKUP_SERVICE_DOCKER_IMAGE_URI:	630013828440.dkr.ecr.us-east-1.amazonaws.com/awscdk-minecraft-cousins-minecraftpaasmcdeployjobdefinitionminecraftserverbackupserviceimageminecraftbackupserviceecrrepo7e27ab78-ex0z7a888orm
      MINECRAFT_SERVER_BACKUPS_BUCKET_NAME:	awscdk-minecraft-cousins-minecraftpaasminecraftse-1ll9k6g2rtbbd
      AWS_ACCOUNT:	630013828440
      BACKUP_SERVICE_ECR_REPO_ARN:	arn:aws:ecr:us-east-1:630013828440:repository/awscdk-minecraft-cousins-minecraftpaasmcdeployjobdefinitionminecraftserverbackupserviceimageminecraftbackupserviceecrrepo7e27ab78-ex0z7a888orm

    volumes:
      - ~/.aws:/root/.aws:ro
    build:
      context: .
      dockerfile: ./Dockerfile
    # volumes:
    #   - .:/app
